services:
  java-app:
    image: java-project2:${BUILD_NUMBER}
    ports:
      - "8083:8081"
    depends_on:
      nginx:
        condition: service_healthy
    environment:
      APP_ENV: ${APP_ENV}
      APP_VERSION: ${APP_VERSION}


  nginx:
    image: nginx
    healthcheck:
      test: ["CMD-SHELL", "nginx -t || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
